name: rossa # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: "0.1.1" # just for humans, typically '1.2+git' or '1.3.2'
summary: Attempt to create a SimpleHTTPServer in Rust. Also inspired by gossa.
description: This is a simple HTTP file server written in Rust.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

parts:
  rossa:
    # See 'snapcraft plugins'
    plugin: rust
    source: https://github.com/rednithin/rossa.git

apps:
  rossa:
    command: bin/rossa
